name: Build and Test C/C++ Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up C/C++ environment
        uses: actions/setup-cpp@v2
        with:
          compiler: 'gcc'  # O 'clang' según tu preferencia

      - name: Build project
        run: make  # Ejecuta el comando 'make' para compilar tu proyecto
